/* eslint-disable quotes, quote-props, comma-dangle */
// GENERATED by ds-eds-tools/eds-fields/build-fields.mjs from component-models.json
// + ds-eds-assets/models/ac-card.ds.json. Do not hand-edit.
export default [
  {
    "name": "image",
    "read": "image",
    "apply": "prop:imagePath",
    "selector": ".cmp-image"
  },
  {
    "name": "pretitle",
    "read": "text",
    "apply": "prop:pretitle",
    "selector": ".cmp-teaser__pretitle"
  },
  {
    "name": "title",
    "read": "text",
    "apply": "prop:title",
    "selector": ".cmp-teaser__title"
  },
  {
    "name": "description",
    "read": "richtext",
    "apply": "prop:description",
    "selector": ".cmp-teaser__description"
  },
  {
    "name": "actionText",
    "read": "text",
    "apply": "action:title",
    "selector": ".cmp-teaser__action-link"
  },
  {
    "name": "actionUrl",
    "read": "href",
    "apply": "action:url",
    "selector": "-"
  },
  {
    "name": "date",
    "read": "text",
    "apply": "prop:date",
    "selector": ".cmp-teaser__date"
  },
  {
    "name": "styleVariant",
    "read": "text",
    "apply": "class",
    "selector": "-",
    "default": "style-primary"
  },
  {
    "name": "cardModifier",
    "read": "text",
    "apply": "class",
    "selector": "-",
    "multi": true
  },
  {
    "name": "cardType",
    "read": "text",
    "apply": "class",
    "selector": "-",
    "default": "ac-core-card-content"
  },
  {
    "name": "headlineClamp",
    "read": "text",
    "apply": "class",
    "selector": "-"
  },
  {
    "name": "descriptionClamp",
    "read": "text",
    "apply": "class",
    "selector": "-"
  },
  {
    "name": "actionText2",
    "read": "text",
    "apply": "action2:title",
    "selector": ".cmp-teaser__action-link:nth-of-type(2)"
  },
  {
    "name": "actionUrl2",
    "read": "href",
    "apply": "action2:url",
    "selector": "-"
  }
];
