import { moveInstrumentation } from '../scripts/scripts.js';

/**
 * Shared, reusable engine that turns a Universal Editor block's cells into
 * DOM-independent values, then folds those values into component props and
 * re-applies live-edit instrumentation — driven entirely by a field
 * descriptor list (see blocks/ac-card/fields.js, generated by
 * ds-eds-tools/eds-fields/build-fields.mjs from component-models.json + the
 * matching ds-eds-assets/models/*.ds.json `_reader` sidecar). Nothing here
 * is ac-card specific; any block whose fields.js follows the same {name,
 * read, apply, selector, default?} shape can reuse this.
 */

// A block's rows come either positional (each row IS the field's content,
// matched by index into FIELDS -- the only shape that ever existed before
// key-value support) or key-value ("key-value": true on the block's
// component-definition.json template -- each row is
// <div><div>fieldName</div><div>value</div></div>, matched by name). Preview
// content is shared across branches and a page's DOM follows whichever
// branch last published it, so a page rendered under old positional code
// can reach new key-value-aware code (and vice versa) at any time -- there
// is no migration step that retires the positional path, so both shapes
// must keep working indefinitely. Detection is per block, at read time: a
// generated flag is not trusted on its own (a page can be stale relative to
// it), so the row list itself is inspected -- if the first row's first
// child's text matches a known FIELDS[] name, every row is read as a
// name/value pair; otherwise the row list falls back to the original
// positional zip, unchanged.
function isKeyValueLayout(cells, FIELDS) {
  const firstRow = cells[0];
  const label = firstRow?.children?.[0];
  if (!label) return false;
  const name = label.textContent.trim();
  return FIELDS.some((field) => field.name === name);
}

// Indexes a key-value row list by field name: each row's first child is the
// authored field name, its second child the value. A row whose first child
// doesn't match any FIELDS[] name (a field this FIELDS list doesn't know
// about, or a malformed row) is skipped -- the field it would have matched
// then reads as unauthored, same as a missing cell in the positional path.
function keyValueRowsByName(cells, FIELDS) {
  const rows = {};
  cells.forEach((row) => {
    const name = row?.children?.[0]?.textContent.trim();
    if (name && FIELDS.some((field) => field.name === name)) {
      rows[name] = row;
    }
  });
  return rows;
}

/**
 * Map `cells` (a block's or item's field divs, in field order) onto values,
 * by index into FIELDS.
 */
export function readCells(cells, FIELDS) {
  const values = {};
  const cellsByName = {};
  const keyValue = isKeyValueLayout(cells, FIELDS);
  const rowsByName = keyValue ? keyValueRowsByName(cells, FIELDS) : null;

  FIELDS.forEach((field, index) => {
    // `row` is the field's own row (used below for instrumentation lookup,
    // which searches the whole row regardless of layout); `cell` is what
    // the read strategies actually read from -- the row's value child in
    // key-value layout, the row itself (unchanged) in positional layout.
    const row = keyValue ? rowsByName[field.name] : cells[index];
    const cell = keyValue ? row?.children?.[1] : row;
    cellsByName[field.name] = row;

    let value;
    switch (field.read) {
      case 'text':
        value = cell?.textContent.trim() || undefined;
        break;
      case 'richtext':
        value = cell?.innerHTML.trim() || undefined;
        break;
      case 'href':
        value = (cell?.querySelector('a')?.getAttribute('href') || cell?.textContent || '').trim();
        break;
      case 'image': {
        // Existing <img>'s src wins if present; otherwise fall back to an
        // http(s):// URL from an authored link or plain cell text. The
        // <picture> element itself (if any) is NOT captured here — it's
        // re-derived by render-card.js's own patchPicture() straight from
        // the cell.
        const existingImg = cell?.querySelector('img');
        if (existingImg) {
          value = existingImg.getAttribute('src');
        } else {
          const url = (cell?.querySelector('a[href]')?.getAttribute('href') || cell?.textContent || '').trim();
          if (/^https?:\/\//.test(url)) value = url;
        }
        break;
      }
      case 'boolean':
        // Universal Editor's boolean/checkbox field renders its value as
        // literal "true"/"false" cell text. NOTE: an explicit `false` here
        // hits the `|| field.default` fallback below (false is falsy) and
        // becomes `undefined` unless the field sets @edsDefault -- harmless
        // for a field whose consumer only checks truthiness (e.g.
        // isDecorative), but a genuine gotcha for one that would need a
        // real `false` to survive.
        value = cell?.textContent.trim().toLowerCase() === 'true';
        break;
      default:
        throw new Error(`field-reader: unknown read strategy "${field.read}" for field "${field.name}"`);
    }

    // A field's `default` (e.g. styleVariant -> style-primary) only kicks
    // in when nothing was authored.
    values[field.name] = value || field.default;
  });

  return { values, cellsByName };
}

// Same shape-detection readCells() applies per field, exposed for a caller
// that reads one field outside the FIELDS/readCells pipeline -- e.g.
// ac-card-local-field.js, which slices its own last cell off before handing
// the rest to ac-card's renderCard() and reads that one field by hand. If
// `row` is a key-value pair (its first child's text is `fieldName`), the
// value child is returned; otherwise `row` itself is returned unchanged, so
// a positional caller's existing `row?.textContent` read keeps working.
export function readNamedCell(row, fieldName) {
  const label = row?.children?.[0];
  if (label && label.textContent.trim() === fieldName) {
    return row.children[1];
  }
  return row;
}

// Writes `value` at `props[path[0]][path[1]]...`, copying each object on the
// way down instead of writing into it, and keeping the keys already set
// beside the target.
function setPath(props, path, value) {
  const [head, ...rest] = path;
  if (rest.length === 0) {
    props[head] = value;
  } else {
    const child = { ...props[head] };
    setPath(child, rest, value);
    props[head] = child;
  }
}

// Page-unique counter backing the action-link id buildProps mints below.
// None of buildProps's current callers (render-card.js, render-banner.js,
// ac-container.js's per-row renderCard() calls) have a real DOM identity
// to hand in -- render-card.js and render-banner.js get their own id from
// uniqueId(), and ac-container.js calls renderCard(cells) once per row
// with no id at all. Counting instead of hard-coding is what makes two
// instances on one page get different action ids.
let actionIdCounter = 0;

/**
 * Apply `prop:`/`action:` strategies from FIELDS to `values`, producing the
 * props object renderCard hands to Teaser(). `class` fields are handled
 * separately by the caller (they become classList additions, not props).
 * actionText + actionUrl fold into one Teaser `actions` entry +
 * `actionsEnabled`. `action2:title` + `action2:url` (card-only second CTA)
 * fold into a second entry after it.
 *
 * `prop:<name>` sets props[name] = value. `prop:<a>.<b>` (any depth) sets a
 * nested value without replacing its siblings: `prop:link.url` produces
 * props.link = { ...props.link, url: value }, so fields that target
 * different keys of the same object (`prop:link.url`, `prop:link.valid`)
 * merge into one object. A missing intermediate object is created.
 *
 * `instanceId` is optional: a caller that DOES have a real per-instance
 * identity (a block's own id, a row's resource path, ...) can pass it to
 * get a stable, meaningful action id instead of the counter-based
 * fallback. No current caller has one, so every existing
 * `buildProps(values, FIELDS)` call still works and gets a unique id from
 * the counter.
 */
export function buildProps(values, FIELDS, instanceId) {
  const props = {};
  let actionTitle;
  let actionUrl;
  let action2Title;
  let action2Url;

  FIELDS.forEach((field) => {
    const { apply } = field;
    // class fields are not Teaser props; "none" fields aren't a Teaser
    // prop OR a literal CSS class on their own -- the render script reads
    // their raw value directly out of `values` instead.
    if (!apply || apply === 'class' || apply === 'none') return;
    const value = values[field.name];
    if (apply.startsWith('prop:')) {
      setPath(props, apply.slice('prop:'.length).split('.'), value);
    } else if (apply === 'action:title') {
      actionTitle = value;
    } else if (apply === 'action:url') {
      actionUrl = value;
    } else if (apply === 'action2:title') {
      action2Title = value;
    } else if (apply === 'action2:url') {
      action2Url = value;
    } else {
      throw new Error(`field-reader: unknown apply strategy "${apply}" for field "${field.name}"`);
    }
  });

  const actionId = `${instanceId ?? `action-${(actionIdCounter += 1)}`}-action`;
  // A second, card-only call-to-action (actionText2/actionUrl2) folds into a
  // SECOND entry after the first. It is independent of the first: with only
  // the second filled it becomes the sole action. With both fields empty
  // the output is byte-identical to the single-action shape (same key order).
  const actions = [];
  if (actionTitle) actions.push({ id: actionId, title: actionTitle, link: { url: actionUrl } });
  if (action2Title) actions.push({ id: `${actionId}-2`, title: action2Title, link: { url: action2Url } });
  props.actionsEnabled = actions.length > 0;
  props.actions = actions;
  return props;
}

// Splits `rawValue` on `delimiter`, trims each piece, drops empties, and
// adds what's left to `root.classList` one token at a time -- shared by
// both branches of applyClassFields below, which differ only in which
// delimiter marks a boundary between classes.
function addClassTokens(root, rawValue, delimiter) {
  rawValue.split(delimiter)
    .map((token) => token.trim())
    .filter(Boolean)
    .forEach((token) => root.classList.add(token));
}

/**
 * Apply `apply: "class"` fields to `root.classList` -- the one thing
 * buildProps() deliberately skips (see its own comment above).
 *
 * A multi-select field's value serializes as a comma-separated string,
 * same convention as EDS's own Section "style" metadata field
 * (scripts/aem.js's decorateSections(): `meta.style.split(',')...`) --
 * each token becomes its own class, never one combined class.
 *
 * A non-multi (single-select) field's value is normally one class with no
 * whitespace, but some real options are legitimately two-or-more
 * space-separated classes for a single authored choice -- e.g. ac-group-lib
 * Button's "Variant" option "Primary Filled" =
 * "cmp-button--primary cmp-button--filled". `classList.add()` throws on a
 * value containing whitespace, so that value is split the same way, just
 * with a different delimiter than the multi-select's comma (comma marks a
 * boundary between separately AUTHORED options; whitespace here marks a
 * boundary WITHIN one authored option's own value).
 */
export function applyClassFields(root, values, FIELDS) {
  FIELDS.filter((field) => field.apply === 'class' && values[field.name]).forEach((field) => {
    const value = values[field.name];
    if (field.multi) {
      addClassTokens(root, value, ',');
    } else {
      addClassTokens(root, value, /\s+/);
    }
  });
}

/**
 * Re-attach each field's live-edit instrumentation from its authored cell
 * onto the rendered element `root.querySelector(field.selector)` finds —
 * only for fields with a real value and a real selector (selector "-"
 * means "not applied via a queryable DOM node", e.g. class-driven or
 * folded-into-actions fields, which carry no instrumentation target of
 * their own).
 *
 * AEM puts `data-aue-prop`/`data-richtext-prop` on the cell's first
 * instrumented descendant, not on the cell div itself -- moveInstrumentation
 * only moves attributes it finds on the node it's given, so the cell's
 * instrumented descendant is what gets passed. Falls back to the cell
 * itself when nothing matches, so a block whose attribute is on the cell
 * still works.
 */
export function instrumentFields(cellsByName, values, root, FIELDS) {
  FIELDS.forEach((field) => {
    if (field.selector === '-' || !values[field.name]) return;
    const cell = cellsByName[field.name];
    const el = root.querySelector(field.selector);
    const instrumented = cell?.querySelector('[data-aue-prop],[data-richtext-prop]') || cell;
    if (instrumented && el) moveInstrumentation(instrumented, el);
  });
}

/**
 * Generic post-render DOM patch: set `attrs` on whatever `selector` finds
 * under `root`, or no-op if nothing matches. Deliberately outside the
 * FIELDS-driven pipeline above (readCells/buildProps/instrumentFields) --
 * those exist to thread a DS-mastered component's own props, and this is
 * for the opposite case: a block-local field with no DS-side equivalent at
 * all (e.g. link-navigation context, an EDS/authoring concern, not
 * something Teaser() should ever model). Kept generic (attribute name +
 * selector + value only) so it's a real reusable addition to this shared
 * engine rather than a one-off hard-coded to any single attribute or
 * field -- the translation from an authored value to concrete attribute
 * values (e.g. a boolean -> "_blank"/"noopener noreferrer") stays
 * block-local logic, in the calling block's own decorate().
 */
export function applyAttributes(root, selector, attrs) {
  const el = root?.querySelector(selector);
  if (!el) return;
  Object.entries(attrs).forEach(([name, value]) => el.setAttribute(name, value));
}
